#!/bin/bash

cd "$(dirname "$0")"

while true
do

  files=$(ls -1 CMA | head -n 1)

  if [ -z $files ]
  then
    echo "no files left, exiting"
    break
  fi

  echo "doing $files"

  # take first image from each folder
  echo "taking first photo from each folder... "
  for i in {A..D}
  do
    cam="CM$i"
    filename=$(ls -1 $cam | head -n 1)
    if [ "$filename" != "" ]
    then
      mv -v $cam/$filename frames/$cam"_"$filename
    fi
  done
  echo "done"

  pushd frames
  filenames=$(ls *.jpg)
  gifname=$(echo $filenames | sed 's/ /-/g')"_"
  echo "gif filename $gifname"

  echo -n "making a pallindrome... "
  python3 pallindrome.py
  echo "done"

  echo "resizing images... "
  mogrify -resize 1000x *.jpg
  echo "done"

  giffilename=$gifname".gif"
  echo -n "creating gif... "
  convert *.jpg -delay 10 -loop 0 $giffilename
  echo "done"


  convert $giffilename -fill '#0008' -fill white -pointsize 20  -annotate +10+41 "$filenames" $giffilename

  mkdir $gifname
  mv *.jpg *.gif $gifname/
  open -a Safari $gifname/$giffilename

  popd

done
