#!/bin/bash
cd "$(dirname "$0")"

while true
do

  for i in {A..D}; do
      n=$(ls -l CM$i/ | wc -l)
      if [ $n -ne 0 ]
      then
          n=$(echo "$n - 1" | bc)
      else
          n=0 #for consistent formatting
      fi
      echo "$i $n"
  done


  sleep 1
  clear
  
done
